name: flutter_firebase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.28.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  # Se precisar de armazenamento no Firebase
  firebase_storage: ^11.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
