// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALfTNOT1Ss-uf487OKfYcpUavLyJSC59U',
    appId: '1:815054289441:web:c5f1a4ade9b0597dbec160',
    messagingSenderId: '815054289441',
    projectId: 'atividadefirebase-3a29a',
    authDomain: 'atividadefirebase-3a29a.firebaseapp.com',
    storageBucket: 'atividadefirebase-3a29a.firebasestorage.app',
    measurementId: 'G-RK85KK9QZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeoqOwaDjxadKwl9OHJfOsHom72mv0CVw',
    appId: '1:815054289441:android:54eee3a4ec31c5a7bec160',
    messagingSenderId: '815054289441',
    projectId: 'atividadefirebase-3a29a',
    storageBucket: 'atividadefirebase-3a29a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgad33apEqK0nnNWswSLd1wCw_wjiyRWo',
    appId: '1:815054289441:ios:ebd70d3ec1eef5f3bec160',
    messagingSenderId: '815054289441',
    projectId: 'atividadefirebase-3a29a',
    storageBucket: 'atividadefirebase-3a29a.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgad33apEqK0nnNWswSLd1wCw_wjiyRWo',
    appId: '1:815054289441:ios:ebd70d3ec1eef5f3bec160',
    messagingSenderId: '815054289441',
    projectId: 'atividadefirebase-3a29a',
    storageBucket: 'atividadefirebase-3a29a.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALfTNOT1Ss-uf487OKfYcpUavLyJSC59U',
    appId: '1:815054289441:web:ce911efd13701ecfbec160',
    messagingSenderId: '815054289441',
    projectId: 'atividadefirebase-3a29a',
    authDomain: 'atividadefirebase-3a29a.firebaseapp.com',
    storageBucket: 'atividadefirebase-3a29a.firebasestorage.app',
    measurementId: 'G-K52JTNHZ4G',
  );
}
